### ISSUE TITLE
Dangerous alternative prefix

### ISSUE THREAD

**Issue by bookerthegeek** [BeetoGuy/BetterWithMods#260]
```
[01:55:59] [Client thread/WARN] [FML]: ****************************************
[01:55:59] [Client thread/WARN] [FML]: * Dangerous alternative prefix `tconstruct` for name `molten_soulforged_steel`, expected `betterwithmods` invalid registry invocation/invalid name?
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:128)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:110)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[01:55:59] [Client thread/WARN] [FML]: ****************************************
[01:55:59] [Client thread/WARN] [FML]: ****************************************
[01:55:59] [Client thread/WARN] [FML]: * Dangerous alternative prefix `tconstruct` for name `molten_soulforged_steel`, expected `betterwithmods` invalid registry invocation/invalid name?
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:128)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:111)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[01:55:59] [Client thread/WARN] [FML]: ****************************************
[01:55:59] [Client thread/WARN] [FML]: ****************************************
[01:55:59] [Client thread/WARN] [FML]: * Dangerous alternative prefix `tconstruct` for name `molten_hellfire`, expected `betterwithmods` invalid registry invocation/invalid name?
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:128)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:110)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[01:55:59] [Client thread/WARN] [FML]: ****************************************
[01:55:59] [Client thread/WARN] [FML]: ****************************************
[01:55:59] [Client thread/WARN] [FML]: * Dangerous alternative prefix `tconstruct` for name `molten_hellfire`, expected `betterwithmods` invalid registry invocation/invalid name?
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[01:55:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:128)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:111)
[01:55:59] [Client thread/WARN] [FML]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[01:55:59] [Client thread/WARN] [FML]: ****************************************
```
Saw this and thought you should know. If this is an issue with tinkers let me know and I'll post over their.
* Better With Mods-0.14.15-1.10.2-hotfix1.jar
* TConstruct-1.10.2-2.6.3.jar

**Comment by BeetoGuy** [comment]
Yeah, that's been bothering me for a while, but I'm not entirely sure how to fix it, and I just put it on the backburner since it doesn't seem to actually break anything.

**Comment by KnightMiner** [comment]
I think officially it is a Tinkers Construct issue, as Tinkers registers the liquid blocks when it is "not its turn" to ensure we only register them if the fluid is actually used (something is in the oredictionary). If you create your own fluid blocks instead it shouldn't cause the warning anymore, though technically it is just a warning and no actual issues will result.
