### ISSUE TITLE
World creation error with Better With Mods 1.1.x, Quark, and Botania

### ISSUE THREAD

**Issue by djsrv** [BeetoGuy/BetterWithMods#288]
The combination of Better With Mods 1.1.x, Quark, and Botania gives this error on world creation:
<img width="966" alt="screen shot 2017-03-26 at 12 11 40 pm" src="https://cloud.githubusercontent.com/assets/16441443/24332950/8c106c0c-121d-11e7-9d9d-12ba75c30370.png">
It doesn't happen with Better With Mods 1.0.8, or if it's just Better With Mods and Quark, Better With Mods and Botania, or Quark and Botania.

[Log with Better With Mods 1.1.1, Quark, and Botania](https://hastebin.com/izavotowow)
[Log with Better With Mods 1.0.8, Quark, and Botania](https://hastebin.com/ayucemukox)

The obvious difference is this:
```
[12:05:26] [Server thread/ERROR]: Exception reading /Applications/MultiMC.app/Contents/MacOS/instances/meme/minecraft/saves/New World/level.dat
java.lang.ArrayIndexOutOfBoundsException: 640
	at net.minecraft.util.IntIdentityHashBiMap.func_186814_a(IntIdentityHashBiMap.java:100) ~[oh.class:?]
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.addObjectRaw(FMLControlledNamespacedRegistry.java:578) ~[FMLControlledNamespacedRegistry.class:?]
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:490) ~[FMLControlledNamespacedRegistry.class:?]
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.loadIds(FMLControlledNamespacedRegistry.java:780) ~[FMLControlledNamespacedRegistry.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.loadPersistentDataToStagingRegistry(PersistentRegistryManager.java:463) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:283) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:329) ~[FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:421) ~[FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [bbu.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122) [bbt.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:74) [cch.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by BeetoGuy** [comment]
Can't seem to replicate in my test instance. I don't think it's an issue with any of those mods.
