### ISSUE TITLE
Unable to load - Crash on game loading

### ISSUE THREAD

**Issue by bookerthegeek** [BeetoGuy/BetterWithMods#320]
## Heyo ##
[Here][1] is a crash for you..

### What Happens ###
Minecraft will not load. This is on a fresh install with no configs. ~~Oddly enough it works when the config is already there in the config folder from the previous version before the update.~~ EDIT: no, it still crashes with the previous config also.

### What I expected to happen ###
Minecraft to load

### Snippet from Crash report ###
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better With Mods (betterwithmods)
Caused by: java.lang.NullPointerException
	at net.minecraftforge.common.config.Configuration.getCategory(Configuration.java:1135)
	at net.minecraftforge.common.config.Configuration.get(Configuration.java:719)
	at net.minecraftforge.common.config.Configuration.get(Configuration.java:211)
	at net.minecraftforge.common.config.Configuration.get(Configuration.java:197)
	at betterwithmods.module.ConfigHelper.loadPropBool(ConfigHelper.java:51)
	at betterwithmods.module.Feature.loadPropBool(Feature.java:150)
	at betterwithmods.module.tweaks.HempSeed.<init>(HempSeed.java:18)
	at betterwithmods.module.tweaks.Tweaks.addFeatures(Tweaks.java:18)
	at betterwithmods.module.Module.setupConfig(Module.java:73)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at betterwithmods.module.ModuleLoader.forEachModule(ModuleLoader.java:137)
	at betterwithmods.module.ModuleLoader.loadModuleConfigs(ModuleLoader.java:122)
	at betterwithmods.module.ModuleLoader.setupConfig(ModuleLoader.java:116)
	at betterwithmods.module.ModuleLoader.preInit(ModuleLoader.java:62)
	at betterwithmods.BWMod.preInit(BWMod.java:100)
```
### Versions ###
- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2296
- Better With Mods: 1.1.8-1.11.2.jar

[1]:https://gist.github.com/bookerthegeek/5807516284c857306aca0d385d11d152

**Comment by primetoxinz** [comment]
Fixed, here is a working build. https://github.com/BeetoGuy/BetterWithMods/releases/tag/1.1.9
