### ISSUE TITLE
1.2.1 client/server crash

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#332]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better With Mods (betterwithmods)
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: TEMPTATION_ITEMS
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:107)
	at betterwithmods.module.tweaks.PigBreeding.init(PigBreeding.java:26)
	at betterwithmods.module.Module.lambda$init$3(Module.java:141)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at betterwithmods.module.Module.forEachEnabled(Module.java:194)
	at betterwithmods.module.Module.init(Module.java:141)
	at betterwithmods.module.ModuleLoader.lambda$init$3(ModuleLoader.java:70)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at betterwithmods.module.ModuleLoader.forEachEnabled(ModuleLoader.java:141)
	at betterwithmods.module.ModuleLoader.init(ModuleLoader.java:70)
	at betterwithmods.BWMod.init(BWMod.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:109)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchFieldException: TEMPTATION_ITEMS
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:98)
	... 41 more

**Comment by primetoxinz** [comment]
.-. I thought I pushed that
