### ISSUE TITLE
1.2.1 "Error executing task" on server

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#333]
Seems like it happens when I jump.

Autojump is also still on, nothing about it in the config.
Don't know if this is supposed to be doing something.
+        jumpExhaustion = loadPropDouble("Jump Exhaustion", "Exhaustion penalty from jumping", 0.09);
 +        if(loadPropBool("Kill Autojump", "Automatically Disable Autojump, because it's stupid",true))
 +            Minecraft.getMinecraft().gameSettings.autoJump = false;

java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
	at betterwithmods.module.hardcore.HCHunger.jumpingPenalty(HCHunger.java:346) ~[HCHunger.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_92_HCHunger_jumpingPenalty_LivingJumpEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingJump(ForgeHooks.java:627) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70664_aZ(EntityLivingBase.java:1732) ~[sw.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70664_aZ(EntityPlayer.java:1781) ~[aay.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:486) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[iz.class:?]
	at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18) ~[iz$b.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by primetoxinz** [comment]
You know, I'll start testing on the server too lol
