### ISSUE TITLE
Lens crash

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#340]
1.2.4

Messing with lenses in a flat world, got this crash. I think a skeleton walked across the beam.

World crashes immediately on load now, I can send a copy if it helps.

net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186332_a(WalkNodeProcessor.java:192) ~[bbg.class:?]
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186320_a(WalkNodeProcessor.java:113) ~[bbg.class:?]
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:82) ~[bbe.class:?]
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40) ~[bbe.class:?]
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30) ~[bbe.class:?]
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:110) ~[wf.class:?]
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:69) ~[we.class:?]
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:89) ~[wf.class:?]
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:139) ~[wf.class:?]
	at net.minecraft.entity.ai.EntityAIFleeSun.func_75249_e(SourceFile:58) ~[ue.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102) ~[uj.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:895) ~[sx.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2258) ~[sw.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:680) ~[sx.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:41) ~[aaa.class:?]
	at net.minecraft.entity.monster.AbstractSkeleton.func_70636_d(SourceFile:141) ~[zm.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088) ~[sw.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384) ~[sx.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:46) ~[aaa.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1963) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) ~[lw.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1932) ~[ajs.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1748) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more

**Comment by primetoxinz** [comment]
yep, it was the skeleton
