### ISSUE TITLE
Server crash - buoy related?

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#343]
1.2.6
Server was crashing on startup.

Tons of mods on the server, and once I deleted the world the crashing stopped, can't reproduce (tried tossing an egg in water).

java.lang.IllegalAccessError: tried to access field net.minecraft.entity.item.EntityItem.field_184533_c from class betterwithmods.common.entity.item.EntityItemBuoy
	at betterwithmods.common.entity.item.EntityItemBuoy.getITEM(EntityItemBuoy.java:62)
	at betterwithmods.common.entity.item.EntityItemBuoy.func_70071_h_(EntityItemBuoy.java:84)
	at net.minecraft.world.World.func_72866_a(World.java:1963)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

Thread: Server thread
Stacktrace:
	at betterwithmods.common.entity.item.EntityItemBuoy.getITEM(EntityItemBuoy.java:62)
	at betterwithmods.common.entity.item.EntityItemBuoy.func_70071_h_(EntityItemBuoy.java:84)
	at net.minecraft.world.World.func_72866_a(World.java:1963)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Entity being ticked --
Details:
	Entity Type: betterwithmods:entity_item_buoy (betterwithmods.common.entity.item.EntityItemBuoy)
	Entity ID: 20
	Entity Name: item.item.egg
	Entity's Exact location: 29.88, 68.00, 285.34
	Entity's Block location: World: (29,68,285), Chunk: (at 13,4,13 in 1,17; contains blocks 16,0,272 to 31,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

**Comment by primetoxinz** [comment]
what version of forge?

**Comment by Coldwire** [comment]
Server is 13.20.0.2282

**Comment by primetoxinz** [comment]
exact same version I'm on, so not that.

**Comment by Coldwire** [comment]
Not a dev environment.

**Comment by primetoxinz** [comment]
yeah, no idea. if it happens again, reopen this but other than that it shouldn't happen
