### ISSUE TITLE
[1.11.2] Sponge Bugs

### ISSUE THREAD

**Issue by tyler489** [BeetoGuy/BetterWithMods#423]
Anytime someone Loads a chunk with a spawner in it the server crashes While Grow Moss near spawners is enabled the server crashes.

It also Doesnt like Your BlockLense
```java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at betterwithmods.common.blocks.BlockLens.getFacingFromBlockState(BlockLens.java:149)
	at betterwithmods.common.blocks.BlockLens.getFacing(BlockLens.java:144)
	at betterwithmods.common.blocks.BlockLens.isFacingBlockDetector(BlockLens.java:185)
	at betterwithmods.common.blocks.BlockLens.func_180650_b(BlockLens.java:75)
	at org.spongepowered.common.event.tracking.TrackingUtil.updateTickBlock(TrackingUtil.java:268)
	at net.minecraft.world.WorldServer.redirect$onUpdateTick$zkd000(WorldServer.java:2201)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:745)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at betterwithmods.common.blocks.BlockLens.getFacingFromBlockState(BlockLens.java:149)
	at betterwithmods.common.blocks.BlockLens.getFacing(BlockLens.java:144)
	at betterwithmods.common.blocks.BlockLens.isFacingBlockDetector(BlockLens.java:185)
	at betterwithmods.common.blocks.BlockLens.func_180650_b(BlockLens.java:75)
	at org.spongepowered.common.event.tracking.TrackingUtil.updateTickBlock(TrackingUtil.java:268)
	at net.minecraft.world.WorldServer.redirect$onUpdateTick$zkd000(WorldServer.java:2201)

-- Block being ticked --
Details:
	Block: betterwithmods:lens[facing=down,lit=true]
	Block location: World: (102,66,226), Chunk: (at 6,4,2 in 6,14; contains blocks 96,0,224 to 111,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:745)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)``

**Comment by primetoxinz** [comment]
Please report these to Sponge, there are not issues on my side.
