### ISSUE TITLE
Better With Mods-1.3.0-1.12.jar Client Crash

### ISSUE THREAD

**Issue by cyberpunkbln** [BeetoGuy/BetterWithMods#478]
Hello,

i have updated Biomes O' Plenty and the newest Forge-Build. Is that an problem with other mods? I think or?

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.12-2.337-full.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  BCModPlugin (zz-backpacks 1.12 - 3.1.9.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.5.7.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 7/13/17 2:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better With Mods (betterwithmods)
Caused by: java.lang.NullPointerException
	at betterwithmods.module.compat.bop.BiomesOPlenty.init(BiomesOPlenty.java:118)
	at betterwithmods.module.Module.lambda$init$3(Module.java:148)
	at java.util.ArrayList.forEach(Unknown Source)
	at betterwithmods.module.Module.forEachEnabled(Module.java:204)
	at betterwithmods.module.Module.init(Module.java:148)
	at betterwithmods.module.CompatModule.init(CompatModule.java:65)
	at betterwithmods.module.ModuleLoader.lambda$init$4(ModuleLoader.java:70)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEachOrdered(Unknown Source)
	at betterwithmods.module.ModuleLoader.forEachEnabled(ModuleLoader.java:178)
	at betterwithmods.module.ModuleLoader.init(ModuleLoader.java:70)
	at betterwithmods.BWMod.init(BWMod.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:625)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:781)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1036824560 bytes (988 MB) / 2657435648 bytes (2534 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn128M -Xms128M -Xmx8G -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2410 Optifine OptiFine_1.12_HD_U_C4 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2410.jar) 
	UCHI	forge{14.21.1.2410} [Minecraft Forge] (forge-1.12-14.21.1.2410.jar) 
	UCHI	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.12 - 3.1.9.jar) 
	UCHI	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHI	actuallyadditions{1.12-r114} [Actually Additions] (ActuallyAdditions-1.12-r114.jar) 
	UCHI	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UCHI	tesla{1.0.60} [TESLA] (Tesla-1.12-1.0.60.jar) 
	UCHI	theoneprobe{1.4.11} [The One Probe] (theoneprobe-1.12-1.4.11.jar) 
	UCHI	immersiveengineering{0.12-64} [Immersive Engineering] (ImmersiveEngineering-0.12-64.jar) 
	UCHI	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UCHI	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHI	cofhcore{4.3.2} [CoFH Core] (CoFHCore-1.12-4.3.2.7-universal.jar) 
	UCHI	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCHI	thermalfoundation{2.3.2} [Thermal Foundation] (ThermalFoundation-1.12-2.3.2.8-universal.jar) 
	UCHI	thermalexpansion{5.3.2} [Thermal Expansion] (ThermalExpansion-1.12-5.3.2.10-universal.jar) 
	UCHE	betterwithmods{1.2.9-1.11.2} [Better With Mods] (Better With Mods-1.3.0-1.12.jar) 
	UCHI	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCHI	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCHI	biomesoplenty{7.0.0.2289} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2289-universal.jar) 
	UCHI	chameleon{1.12-4.1.1} [Chameleon] (Chameleon-1.12-4.1.1.jar) 
	UCHI	chisel{MC1.12-0.0.13.12} [Chisel] (Chisel-MC1.12-0.0.13.12.jar) 
	UCHI	clayworldgen{1.1.0-1.12} [Clay WorldGen] (ClayWorldGen-1.1.0-1.12.0.jar) 
	UCHI	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCHI	dailies{1.12-6} [Bailey's Dailies] (dailies-1.12-6.jar) 
	UCHI	movingworld{1.12-2.337} [Moving World] (movingworld-1.12-2.337-full.jar) 
	UCHI	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-2.331-full.jar) 
	UCHI	dsurround{3.4.5.7} [Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.5.7.jar) 
	UCHI	presets{3.4.5.7} [Presets!] (DynamicSurroundings-1.12-3.4.5.7.jar) 
	UCHI	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHI	shetiphiancore{3.5.0.1} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.1.jar) 
	UCHI	endertanks{1.6.0.1} [EnderTanks] (endertanks-1.12.0-1.6.0.1.jar) 
	UCHI	extrautils2{1.0} [extrautils2] (extrautils2-1.12-1.5.jar) 
	UCHI	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHI	bigreactors{1.12-0.4.5.33} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.33.jar) 
	UCHI	forestry{5.4.3.131} [Forestry] (forestry_1.12-5.4.3.131.jar) 
	UCHI	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHI	fp{26.1.1} [Futurepack] (Futurepack-1.12-26.1.1.jar) 
	UCHI	fp.api{1.1.0} [Futurepack API] (Futurepack-1.12-26.1.1.jar) 
	UCHI	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHI	hardcoreore{0.0.2} [Hardcore ORE] (hardcoreore-1.12-0.0.2.jar) 
	UCHI	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCHI	improvedextraction{0.1.2-BETA} [Improved Extraction] (ImprovedExtraction-1.12-0.1.2-BETA.jar) 
	UCHI	teslacorelib{@@VERSION@@} [Tesla Core Lib] (tesla-core-lib-1.12-1.0.3.jar) 
	UCHI	industrialforegoing{1.11.2-1.0-BETA} [Industrial Foregoing] (industrialforegoing-1.12-1.0-BETA-16.jar) 
	UCHI	infinitefluids{1.1.1} [InfiniteFluids] (infinitefluids-1.11-1.1.1.jar) 
	UCHI	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHI	modnametooltip{1.8.1} [Mod Name Tooltip] (modnametooltip_1.12-1.8.1.jar) 
	UCHI	moreoverlays{1.12} [MoreOverlays] (moreoverlays-1.12-mc1.12.jar) 
	UCHI	multibeds{1.4.0.1} [Multi-Beds] (multibeds-1.12.0-1.4.0.1.jar) 
	UCHI	multistorage{1.4.0.1} [Multi-Storage] (multistorage-1.12.0-1.4.0.1.jar) 
	UCHI	platforms{1.4.0.1} [Platforms] (platforms-1.12.0-1.4.0.1.jar) 
	UCHI	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHI	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UCHI	recipemanipulator{1.0} [RecipeManipulator] (RecipeManipulator-1.12-0.3.0.11.jar) 
	UCHI	redstonearsenal{2.3.2} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.2.6-universal.jar) 
	UCHI	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.7.jar) 
	UCHI	refinedstorage{1.5.8} [Refined Storage] (refinedstorage-1.5.8.jar) 
	UCHI	rftools{6.10} [RFTools] (rftools-1.12-6.10beta4.jar) 
	UCHI	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8beta1.jar) 
	UCHI	rftoolsdim{5.02} [RFTools Dimensions] (rftoolsdim-1.12-5.02beta3.jar) 
	UCHI	silentlib{2.2.6} [Silent Lib] (SilentLib-1.12-2.2.6-83.jar) 
	UCHI	silentgems{2.4.2} [Silent's Gems] (SilentsGems-1.12-2.4.2-206.jar) 
	UCHI	sgextraparts{1.3.1} [Silent's Gems: Extra Parts] (SGExtraParts-1.12-1.3.1-25.jar) 
	UCHI	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCHI	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UCHI	thermalcultivation{0.1.0} [Thermal Cultivation] (ThermalCultivation-1.12-0.1.0.5-universal.jar) 
	UCHI	thermaldynamics{2.3.2} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.2.9-universal.jar) 
	UCHI	toolbelt{1.6.4} [Tool Belt] (ToolBelt-1.12.0-1.6.4.jar) 
	UCHI	torohealthmod{1.12-11} [ToroHealth Damage Indicators] (torohealth-1.12-11.jar) 
	UCHI	treechopper{1.2.1} [Tree Chopper] (TreeChopper-1.12-1.2.1.jar) 
	UCHI	xaerominimap{1.13.2} [Xaero's Minimap] (Xaeros_Minimap_FP1.13.2_Forge_1.12.jar) 
	UCHI	teslacoreregistries{@@VERSION@@} [Tesla Core Registries] (tesla-core-lib-1.12-1.0.3.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-1.12-2.337-full.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  shetiphian.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
BCModPlugin (zz-backpacks 1.12 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.5.7.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 950M/PCIe/SSE2'
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 950M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

Thx
I have waited for the 1.12 Version, Minecraft is toooooo easy without BWM:).

**Comment by BeetoGuy** [comment]
Oh, I never checked to see if the addons register the blocks through the registry event.

**Comment by primetoxinz** [comment]
@BeetoGuy use `@ObjectHolder`

**Comment by BeetoGuy** [comment]
Nah, that seems fine, it's just pointing to the modded siding recipes.

**Comment by BeetoGuy** [comment]
Okay, after making sure the recipes get registered, it looks like it isn't happening anymore.
