### ISSUE TITLE
Crash when placing Mill

### ISSUE THREAD

**Issue by darkphan** [BeetoGuy/BetterWithMods#511]
BetterWithMods Version: 1.12-2.0.0-61

When placing the mill the game crashes.

Description: Ticking block entity

java.lang.AbstractMethodError: Method betterwithmods/common/blocks/mechanical/tile/TileEntityMill.getWorld()Lnet/minecraft/world/World; is abstract
	at betterwithmods.common.blocks.mechanical.tile.TileEntityMill.getWorld(TileEntityMill.java)
	at betterwithmods.api.tile.IMechanicalPower.overpowerChance(IMechanicalPower.java:40)
	at betterwithmods.api.tile.IMechanicalPower.calculateInput(IMechanicalPower.java:32)
	at betterwithmods.common.blocks.mechanical.tile.TileEntityMill.func_73660_a(TileEntityMill.java:61)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at betterwithmods.common.blocks.mechanical.tile.TileEntityMill.getWorld(TileEntityMill.java)
	at betterwithmods.api.tile.IMechanicalPower.overpowerChance(IMechanicalPower.java:40)
	at betterwithmods.api.tile.IMechanicalPower.calculateInput(IMechanicalPower.java:32)
	at betterwithmods.common.blocks.mechanical.tile.TileEntityMill.func_73660_a(TileEntityMill.java:61)

-- Block entity being ticked --
Details:
	Name: minecraft:bwm.millstone // betterwithmods.common.blocks.mechanical.tile.TileEntityMill
	Block type: ID #535 (tile.bwm:single_machine // betterwithmods.common.blocks.mechanical.BlockMechMachines)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (553,78,183), Chunk: (at 9,4,7 in 34,11; contains blocks 544,0,176 to 559,255,191), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #535 (tile.bwm:single_machine // betterwithmods.common.blocks.mechanical.BlockMechMachines)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

**Comment by primetoxinz** [comment]
[Here](http://ci.blamejared.com/job/BetterWithMods/63/) you go
